// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateSource } from "./CandidateSource";

export type AppCandidate = { name: string, exePath: string, args?: string, workingDir?: string, processName: string, iconBase64?: string, source: CandidateSource, suggested: boolean, };
