// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnClose } from "./OnClose";
import type { ProcessNameMode } from "./ProcessNameMode";

export type AppItem = { id: string, name: string, exePath: string, args?: string, workingDir?: string, processName: string, processNameMode: ProcessNameMode, iconBase64?: string, delayMs: number, runAsAdmin: boolean, startMinimized: boolean, waitForSimConnect: boolean, onClose: OnClose, enabled: boolean, };
