// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnClose } from "./OnClose";

export type AppItem = { id: string, name: string, exePath: string, args?: string, workingDir?: string, processName: string, iconBase64?: string, delayMs: number, runAsAdmin: boolean, onClose: OnClose, enabled: boolean, };
