// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppCandidate } from "./AppCandidate";
import type { UrlCandidate } from "./UrlCandidate";

export type DroppedCandidate = { "type": "app" } & AppCandidate | { "type": "url" } & UrlCandidate;
