// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DroppedCandidate } from "./DroppedCandidate";
import type { RejectedDrop } from "./RejectedDrop";

export type DropResolution = { candidates: Array<DroppedCandidate>, rejected: Array<RejectedDrop>, };
