// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorKind = "io" | "json" | "validation" | "profileNotFound" | "lastProfile" | "executableNotFound" | "launchFailed" | "processNotDetected" | "elevationDenied" | "accessDenied" | "closeTimedOut" | "sessionInProgress" | "autostart" | "unsupported" | "internal";
