// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorPayload } from "./ErrorPayload";
import type { ItemStatus } from "./ItemStatus";

export type ItemRuntime = { itemId: string, status: ItemStatus, launchedByApp: boolean, error?: ErrorPayload, };
