// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemStatus = "pending" | "waitingSimConnect" | "launching" | "running" | "restarting" | "skipped" | "closing" | "closed" | "error";
