// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppItem } from "./AppItem";
import type { UrlItem } from "./UrlItem";

export type LaunchItem = { "type": "app" } & AppItem | { "type": "url" } & UrlItem;
