// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRuntime } from "./ItemRuntime";
import type { MonitorState } from "./MonitorState";

export type MonitorSnapshot = { state: MonitorState, sessionProfileId: string | null, isTestSession: boolean, items: Array<ItemRuntime>, };
