// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaunchItem } from "./LaunchItem";
import type { Trigger } from "./Trigger";

export type Profile = { id: string, name: string, trigger: Trigger, items: Array<LaunchItem>, enabled: boolean, };
