// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DropRejection } from "./DropRejection";

export type RejectedDrop = { path: string, reason: DropRejection, };
