// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Language } from "./Language";
import type { Theme } from "./Theme";

export type Settings = { activeProfileId: string | null, startWithWindows: boolean, startMinimized: boolean, gracefulTimeoutMs: number, closeOnlyIfLaunchedByApp: boolean, theme: Theme, language: Language, onboardingCompleted: boolean, checkUpdatesOnStartup: boolean, };
