// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineKind = "sessionStarted" | "launched" | "skipped" | "notRunning" | "closedGracefully" | "forceClosed" | "kept" | "processNameLearned" | "simConnectReady" | "simConnectWaitSkipped" | "closeDelayed" | "simulatorReturned" | "simulatorStarted" | "simulatorNotStarted" | "keptByUser" | "crashed" | "relaunched" | "error" | "sessionEnded";
