// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineKind } from "./TimelineKind";

export type TimelineEntry = { timestampMs: number, kind: TimelineKind, itemId?: string, itemName?: string, message: string, };
