name: Suggest a feature
description: An idea to improve AutoStart.
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does it solve?
      placeholder: "When I fly with ..., I need ..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
